# Generated by Django 5.1.4 on 2024-12-18 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bast_App', '0002_alter_items_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='image',
            field=models.ImageField(blank=True, upload_to='feedback/'),
        ),
    ]
